<?php

function postermaker_gr2018_menu() {
  $items = array();
  $items['plaatjesmaker'] = array(
    'title' => 'SP Plaatjesmaker',
    'type' => MENU_NORMAL_ITEM,
    // 'access callback' => 'user_is_logged_in',
    'access callback' => TRUE,
  );
  return $items;
}

function postermaker_gr2018_page_delivery_callback_alter(&$delivery_callback){
  $router_item = menu_get_item();
  if ($router_item['path'] === 'plaatjesmaker') {
      $delivery_callback = 'postermaker_gr2018_content';
  }
}

function postermaker_gr2018_content () { 
  global $base_path;  
  $module_path = drupal_get_path('module','postermaker_gr2018');
  $src_path = $base_path . $module_path;
  $html = file_get_contents(dirname(__FILE__).'/postermaker_gr2018.html');
  print str_replace('{$src_path}',$src_path,$html);
}
